version: '3.8'

services:
  backend:
    build:
      context: ./back-end-doc-ia
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./app-documents-ia
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend